# Site settings
title: Nathan Krischer portfolio
email: me@nathankrischer.com
description: >
  Personal and portfolio site for Nathan Krischer, a UX designer in the Washington, DC area.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nathankrischer.com" # the base hostname & protocol for your site
twitter_username: nkzar
github_username:  nkrisc

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [node_modules, Gulpfile.js, README.md, .gitignore, package-lock.json, pacakge.json]
